"""
Pydantic Schemas Package

Contains all validation and serialization schemas.
"""
# Import all schemas
from app.schemas.asset import (
    AssetBase,
    AssetCreate,
    AssetUpdate,
    AssetResponse,
    AssetListItem,
    AssetUploadResponse,
    AssetProcessRequest,
    AssetProcessingStatus,
    GeometryStats,
    AssetOutput,
    QuiltOutput,
    AssetOutputs,
)
from app.schemas.common import (
    APIResponse,
    ErrorResponse,
    UUIDModel,
    TimestampModel,
    SoftDeleteModel,
    PaginatedResponse,
    PaginationMeta,
    MessageResponse,
    HealthResponse,
)
from app.schemas.device import (
    DeviceBase,
    DeviceRegister,
    DeviceActivate,
    DeviceUpdate,
    DeviceCommand,
    DeviceHeartbeat,
    SystemHealth,
    NetworkInfo,
    DeviceResponse,
    DeviceStats,
    DeviceListResponse,
    HardwareType,
)
from app.schemas.organization import (
    OrganizationBase,
    OrganizationCreate,
    OrganizationUpdate,
    OrganizationResponse,
    OrganizationTierUpdate,
    OrganizationStats,
)
from app.schemas.playlist import (
    PlaylistBase,
    PlaylistCreate,
    PlaylistUpdate,
    PlaylistItemsUpdate,
    PlaylistAssignRequest,
    PlaylistUnassignRequest,
    PlaylistResponse,
    PlaylistWithItemsResponse,
    PlaylistItemCreate,
    PlaylistItemUpdate,
    PlaylistItemResponse,
    ScheduleConfig,
    RecurrenceConfig,
)
from app.schemas.token import (
    TokenPayload,
    TokenResponse,
    LoginRequest,
    RefreshTokenRequest,
    LogoutRequest,
    MFASetupResponse,
    MFAVerifyRequest,
    MFADisableRequest,
)
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserRegister,
    UserInvite,
    UserUpdate,
    UserPasswordChange,
    UserPasswordReset,
    UserPasswordResetRequest,
    UserResponse,
    UserMe,
    UserProfile,
)

__all__ = [
    # Common
    "APIResponse",
    "ErrorResponse",
    "UUIDModel",
    "TimestampModel",
    "SoftDeleteModel",
    "PaginatedResponse",
    "PaginationMeta",
    "MessageResponse",
    "HealthResponse",
    # Token/Auth
    "TokenPayload",
    "TokenResponse",
    "LoginRequest",
    "RefreshTokenRequest",
    "LogoutRequest",
    "MFASetupResponse",
    "MFAVerifyRequest",
    "MFADisableRequest",
    # Organization
    "OrganizationBase",
    "OrganizationCreate",
    "OrganizationUpdate",
    "OrganizationResponse",
    "OrganizationTierUpdate",
    "OrganizationStats",
    # User
    "UserBase",
    "UserCreate",
    "UserRegister",
    "UserInvite",
    "UserUpdate",
    "UserPasswordChange",
    "UserPasswordReset",
    "UserPasswordResetRequest",
    "UserResponse",
    "UserMe",
    "UserProfile",
    # Device
    "DeviceBase",
    "DeviceRegister",
    "DeviceActivate",
    "DeviceUpdate",
    "DeviceCommand",
    "DeviceHeartbeat",
    "SystemHealth",
    "NetworkInfo",
    "DeviceResponse",
    "DeviceStats",
    "DeviceListResponse",
    "HardwareType",
    # Asset
    "AssetBase",
    "AssetCreate",
    "AssetUpdate",
    "AssetResponse",
    "AssetListItem",
    "AssetUploadResponse",
    "AssetProcessRequest",
    "AssetProcessingStatus",
    "GeometryStats",
    "AssetOutput",
    "QuiltOutput",
    "AssetOutputs",
    # Playlist
    "PlaylistBase",
    "PlaylistCreate",
    "PlaylistUpdate",
    "PlaylistItemsUpdate",
    "PlaylistAssignRequest",
    "PlaylistUnassignRequest",
    "PlaylistResponse",
    "PlaylistWithItemsResponse",
    "PlaylistItemCreate",
    "PlaylistItemUpdate",
    "PlaylistItemResponse",
    "ScheduleConfig",
    "RecurrenceConfig",
]
